# Case NPS Preditivo - Limpeza e Tratamentos dos Dados

## Pacotes

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

## Leitura de Dados

In [2]:
#load dos dados
dados = pd.read_csv("https://raw.githubusercontent.com/braga0m/TechChallenge1/refs/heads/main/dados/desafio_nps_fase_1.csv")

In [3]:
#20 primeiras linhas dos dados
dados.head(10)

,customer_id,customer_age,customer_region,customer_tenure_months,order_id,order_value,items_quantity,discount_value,payment_installments,delivery_time_days,delivery_delay_days,freight_value,delivery_attempts,customer_service_contacts,resolution_time_days,nps_score,repeat_purchase_30d,complaints_count,csat_internal_score
0,1,63,Nordeste,14,50001,139.73,4,39.35,4,2,2,55.53,3,0,4,6.9,0,3,6.5
1,2,20,Sul,1,50002,458.95,2,9.51,10,6,4,28.23,3,0,10,2.4,0,3,0.0
2,3,46,Nordeste,111,50003,507.06,5,42.82,6,6,1,40.99,1,4,5,4.8,0,7,1.5
3,4,52,Centro-Oeste,117,50004,302.19,2,19.58,9,5,2,35.24,3,1,11,5.9,0,4,0.3
4,5,56,Norte,50,50005,253.06,1,29.37,11,13,1,39.32,1,1,0,6.1,0,3,7.9
5,6,35,Sudeste,75,50006,568.76,6,36.58,3,4,5,41.82,2,2,3,0.9,0,5,1.5
6,7,37,Sudeste,68,50007,41.29,3,99.62,6,8,3,35.83,3,3,4,1.4,0,6,0.6
7,8,60,Sul,37,50008,428.76,4,29.54,10,11,5,44.50,1,0,2,0.0,0,2,4.1
8,9,40,Sul,60,50009,121.56,3,91.95,6,6,3,24.88,2,1,9,6.2,0,3,0.8
9,10,51,Sudeste,70,50010,411.01,6,37.47,3,9,2,30.59,1,0,7,2.7,0,2,4.2

In [ ]:
#informações básica dos dados
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                2500 non-null   int64
 1   customer_age               2500 non-null   int64
 2   customer_region            2500 non-null   object
 3   customer_tenure_months     2500 non-null   int64
 4   order_id                   2500 non-null   int64
 5   order_value                2500 non-null   float64
 6   items_quantity             2500 non-null   int64
 7   discount_value             2500 non-null   float64
 8   payment_installments       2500 non-null   int64
 9   delivery_time_days         2500 non-null   int64
 10  delivery_delay_days        2500 non-null   int64
 11  freight_value              2500 non-null   float64
 12  delivery_attempts          2500 non-null   int64
 13  customer_service_contacts  2500 non-null   int64
 14  resolution_time_days       2500 non-null   int64
 15  nps_score                  2500 non-null   float64
 16  repeat_purchase_30d        2500 non-null   int64
 17  complaints_count           2500 non-null   int64
 18  csat_internal_score        2500 non-null   float64
dtypes: float64(5), int64(13), object(1)
memory usage: 371.2+ KB

In [ ]:
#tamanho dos dados
dados.shape

(2500, 19)

In [ ]:
#summary dos dados
dados.describe().round(3)

,customer_id,customer_age,customer_tenure_months,order_id,order_value,items_quantity,discount_value,payment_installments,delivery_time_days,delivery_delay_days,freight_value,delivery_attempts,customer_service_contacts,resolution_time_days,nps_score,repeat_purchase_30d,complaints_count,csat_internal_score
count,2500.000,2500.000,2500.000,2500.000,2500.000,2500.000,2500.000,2500.000,2500.000,2500.000,2500.000,2500.000,2500.000,2500.000,2500.000,2500.000,2500.000,2500.000
mean,1250.500,43.396,61.322,51250.500,434.260,3.471,29.746,6.004,8.022,2.187,38.217,2.006,1.520,5.486,4.379,0.087,4.150,2.942
std,721.832,14.888,34.479,721.832,289.772,1.687,29.226,3.160,3.770,1.454,12.076,0.815,1.232,3.458,2.510,0.282,1.784,2.379
min,1.000,18.000,1.000,50001.000,7.760,1.000,0.020,1.000,2.000,0.000,2.620,1.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,625.750,31.000,31.000,50625.750,220.245,2.000,8.885,3.000,5.000,1.000,29.928,1.000,1.000,2.000,2.600,0.000,3.000,0.700
50%,1250.500,43.000,62.000,51250.500,375.515,3.000,20.935,6.000,8.000,2.000,38.500,2.000,1.000,6.000,4.400,0.000,4.000,2.800
75%,1875.250,56.000,91.000,51875.250,577.290,5.000,40.832,9.000,11.000,3.000,46.270,3.000,2.000,8.000,6.100,0.000,5.000,4.800
max,2500.000,69.000,119.000,52500.000,1983.810,6.000,230.330,11.000,14.000,8.000,76.130,3.000,7.000,11.000,10.000,1.000,11.000,10.000

In [ ]:
#checagem de duplicadas nos identificadores
a = len(dados["customer_id"].unique())
b = len(dados["order_id"].unique())

#não há duplicadatas nos identificadores
print(a,b)

2500 2500

In [ ]:

#não há nenhuma linha duplicada
dados.drop_duplicates()

,customer_id,customer_age,customer_region,customer_tenure_months,order_id,order_value,items_quantity,discount_value,payment_installments,delivery_time_days,delivery_delay_days,freight_value,delivery_attempts,customer_service_contacts,resolution_time_days,nps_score,repeat_purchase_30d,complaints_count,csat_internal_score
0,1,63,Nordeste,14,50001,139.73,4,39.35,4,2,2,55.53,3,0,4,6.9,0,3,6.5
1,2,20,Sul,1,50002,458.95,2,9.51,10,6,4,28.23,3,0,10,2.4,0,3,0.0
2,3,46,Nordeste,111,50003,507.06,5,42.82,6,6,1,40.99,1,4,5,4.8,0,7,1.5
3,4,52,Centro-Oeste,117,50004,302.19,2,19.58,9,5,2,35.24,3,1,11,5.9,0,4,0.3
4,5,56,Norte,50,50005,253.06,1,29.37,11,13,1,39.32,1,1,0,6.1,0,3,7.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,2496,51,Sul,96,52496,615.81,6,11.41,2,14,3,28.96,2,1,2,3.7,0,3,4.3
2496,2497,37,Sul,89,52497,73.03,1,36.44,3,12,2,27.42,2,2,7,3.7,0,4,2.5
2497,2498,19,Sudeste,98,52498,522.78,1,4.84,9,2,2,38.94,1,1,1,7.4,0,3,6.2
2498,2499,41,Sul,51,52499,55.87,2,2.11,2,14,5,29.10,3,3,0,2.3,0,5,1.7
2499,2500,35,Nordeste,109,52500,420.94,1,16.51,4,11,1,34.16,3,1,0,10.0,1,2,7.6

## Criação e modificando variáveis

In [ ]:
#criando as categorias a partir do nps_score
# aparentemente np.select() é mais eficiente
dados["nps_categoria"] = dados["nps_score"].case_when([
    (dados["nps_score"] >= 9, "Promotores"),
    ((dados["nps_score"] >= 7) & (dados["nps_score"] < 9), "Neutros"),
    ((dados["nps_score"] >= 0) & (dados["nps_score"] < 7), "Detratores")
    ])


dados[["nps_score", "nps_categoria", "csat_internal_score"]].head(20)

    nps_score nps_categoria  csat_internal_score
0         6.9    Detratores                  6.5
1         2.4    Detratores                  0.0
2         4.8    Detratores                  1.5
3         5.9    Detratores                  0.3
4         6.1    Detratores                  7.9
5         0.9    Detratores                  1.5
6         1.4    Detratores                  0.6
7         0.0    Detratores                  4.1
8         6.2    Detratores                  0.8
9         2.7    Detratores                  4.2
10        5.3    Detratores                  2.7
11        7.0       Neutros                  5.8
12        3.7    Detratores                  0.4
13        2.9    Detratores                  3.5
14        2.7    Detratores                  2.4
15        6.0    Detratores                  0.0
16        1.9    Detratores                  2.7
17        4.8    Detratores                  0.0
18        3.4    Detratores                  2.0
19        2.0    Detratores                  5.0

In [ ]:
#variável categórica se teve reclamação ou não
dados["complaints"] = np.where(dados["complaints_count"] > 0, 1, 0)

dados[["complaints", "complaints_count"]].head(20)

    complaints  complaints_count
0            1                 3
1            1                 3
2            1                 7
3            1                 4
4            1                 3
5            1                 5
6            1                 6
7            1                 2
8            1                 3
9            1                 2
10           1                 6
11           1                 2
12           1                 4
13           1                 2
14           1                 3
15           1                 2
16           1                 4
17           1                 4
18           1                 4
19           1                 4

In [ ]:
###dias de atraso
dados["delay_categoria"] = dados["delivery_delay_days"].case_when([
    (dados["delivery_delay_days"] == 0, "0"),
    (dados["delivery_delay_days"] == 1, "1"),
    (dados["delivery_delay_days"] == 2, "2"),
    (dados["delivery_delay_days"] == 3, "3"),
    (dados["delivery_delay_days"].isin([4,5,6,7,8]), "4+"),
])

###
dados["delay_categoria"] = pd.Categorical(
    dados["delay_categoria"],
    categories=["0", "1", "2", "3", "4+"],
    ordered=True
)

###
dados[["delivery_delay_days", "delay_categoria"]].head(20)

    delivery_delay_days delay_categoria
0                     2               2
1                     4              4+
2                     1               1
3                     2               2
4                     1               1
5                     5              4+
6                     3               3
7                     5              4+
8                     3               3
9                     2               2
10                    2               2
11                    1               1
12                    2               2
13                    1               1
14                    3               3
15                    3               3
16                    2               2
17                    3               3
18                    4              4+
19                    2               2

In [ ]:
####
dados["repeat_purchase_30d_labeled"] = dados["repeat_purchase_30d"].case_when([
    (dados["repeat_purchase_30d"] == 0, "Não"),
    (dados["repeat_purchase_30d"] == 1, "Sim"),
])

## Renomeando as colunas

In [ ]:
#renomeando as colunas
dados2 = dados.rename(columns = {
"customer_id": "Cliente ID",
"order_id": "Pedido ID",
"customer_age": "Idade do cliente",
"customer_region": "Região do Cliente",
"customer_tenure_months": "Tempo de relacionamento com o cliente",
"order_value": "Valor do pedido",
"items_quantity": "Quantidade de itens",
"discount_value": "Valor do desconto",
"payment_installments": "Número de parcelas",
"delivery_time_days": "Tempo total da entrega",
"delivery_delay_days": "Tempo de atraso da entrega",
"freight_value": "Valor do frete",
"delivery_attempts": "Número de tentativas de entrega",
"customer_service_contacts": "Número atendimentos",
"resolution_time_days": "Tempo de resolucão de problemas",
"complaints_count": "Número de reclamações",
"repeat_purchase_30d": "Recompra em 30 dias",
"complaints": "Reclamação",
"nps_score": "NPS escore",
"csat_internal_score": "CSAT escore interno",
"delay_categoria": "Dias de atraso na entrega",
"repeat_purchase_30d_labeled": "Recompra em 30 dias (ajustado)",
"nps_categoria":" NPS categoria"
})

In [ ]:
dados2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 23 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Cliente ID                             2500 non-null   int64
 1   Idade do cliente                       2500 non-null   int64
 2   Região do Cliente                      2500 non-null   object
 3   Tempo de relacionamento com o cliente  2500 non-null   int64
 4   Pedido ID                              2500 non-null   int64
 5   Valor do pedido                        2500 non-null   float64
 6   Quantidade de itens                    2500 non-null   int64
 7   Valor do desconto                      2500 non-null   float64
 8   Número de parcelas                     2500 non-null   int64
 9   Tempo total da entrega                 2500 non-null   int64
 10  Tempo de atraso da entrega             2500 non-null   int64
 11  Valor do frete                         2500 non-null   float64
 12  Número de tentativas de entrega        2500 non-null   int64
 13  Número atendimentos                    2500 non-null   int64
 14  Tempo de resolucão de problemas        2500 non-null   int64
 15  NPS escore                             2500 non-null   float64
 16  Recompra em 30 dias                    2500 non-null   int64
 17  Número de reclamações                  2500 non-null   int64
 18  CSAT escore interno                    2500 non-null   float64
 19  nps_categoria                          2500 non-null   object
 20  Reclamação                             2500 non-null   int64
 21  Dias de atraso na entrega              2500 non-null   category
 22  Recompra em 30 dias (ajustado)         2500 non-null   object
dtypes: category(1), float64(5), int64(14), object(3)
memory usage: 432.5+ KB

In [ ]:
dados2.head(20)

,Cliente ID,Idade do cliente,Região do Cliente,Tempo de relacionamento com o cliente,Pedido ID,Valor do pedido,Quantidade de itens,Valor do desconto,Número de parcelas,Tempo total da entrega,...,Número atendimentos,Tempo de resolucão de problemas,NPS escore,Recompra em 30 dias,Número de reclamações,CSAT escore interno,nps_categoria,Reclamação,Dias de atraso na entrega,Recompra em 30 dias (ajustado)
0,1,63,Nordeste,14,50001,139.73,4,39.35,4,2,...,0,4,6.9,0,3,6.5,Detratores,1,2,Não
1,2,20,Sul,1,50002,458.95,2,9.51,10,6,...,0,10,2.4,0,3,0.0,Detratores,1,4+,Não
2,3,46,Nordeste,111,50003,507.06,5,42.82,6,6,...,4,5,4.8,0,7,1.5,Detratores,1,1,Não
3,4,52,Centro-Oeste,117,50004,302.19,2,19.58,9,5,...,1,11,5.9,0,4,0.3,Detratores,1,2,Não
4,5,56,Norte,50,50005,253.06,1,29.37,11,13,...,1,0,6.1,0,3,7.9,Detratores,1,1,Não
5,6,35,Sudeste,75,50006,568.76,6,36.58,3,4,...,2,3,0.9,0,5,1.5,Detratores,1,4+,Não
6,7,37,Sudeste,68,50007,41.29,3,99.62,6,8,...,3,4,1.4,0,6,0.6,Detratores,1,3,Não
7,8,60,Sul,37,50008,428.76,4,29.54,10,11,...,0,2,0.0,0,2,4.1,Detratores,1,4+,Não
8,9,40,Sul,60,50009,121.56,3,91.95,6,6,...,1,9,6.2,0,3,0.8,Detratores,1,3,Não
9,10,51,Sudeste,70,50010,411.01,6,37.47,3,9,...,0,7,2.7,0,2,4.2,Detratores,1,2,Não
10,11,50,Centro-Oeste,28,50011,616.17,2,23.00,8,4,...,0,7,5.3,0,6,2.7,Detratores,1,2,Não
11,12,67,Norte,81,50012,509.48,2,10.42,1,11,...,1,3,7.0,0,2,5.8,Neutros,1,1,Não
12,13,65,Centro-Oeste,85,50013,588.28,6,12.54,5,11,...,1,9,3.7,0,4,0.4,Detratores,1,2,Não
13,14,27,Sudeste,42,50014,165.19,5,52.82,5,10,...,0,8,2.9,0,2,3.5,Detratores,1,1,Não
14,15,50,Sudeste,113,50015,220.81,3,30.73,6,7,...,1,4,2.7,0,3,2.4,Detratores,1,3,Não
15,16,64,Norte,114,50016,732.83,2,13.24,8,9,...,1,8,6.0,0,2,0.0,Detratores,1,3,Não
16,17,50,Norte,70,50017,391.66,4,0.25,11,3,...,1,6,1.9,0,4,2.7,Detratores,1,2,Não
17,18,65,Sul,21,50018,483.04,1,28.08,1,12,...,1,10,4.8,0,4,0.0,Detratores,1,3,Não
18,19,43,Sul,86,50019,383.98,3,33.61,11,3,...,2,3,3.4,0,4,2.0,Detratores,1,4+,Não
19,20,37,Centro-Oeste,74,50020,288.93,2,20.80,9,9,...,1,3,2.0,0,4,5.0,Detratores,1,2,Não

## Exportação

In [ ]:
#exportação das bases de dados
dados.to_csv('dados_ecommerce.csv', index=False)
dados2.to_csv('dados_ecommerce_renomeado.csv', index=False)